"""new migration

Revision ID: 25fe0ffd85bc
Revises: 092caf218d5b
Create Date: 2025-03-15 08:46:45.066418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25fe0ffd85bc'
down_revision: Union[str, None] = '092caf218d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('coingekoid', sa.String(), nullable=False))
    op.drop_index('ix_coins_symbol', table_name='coins')
    op.create_index(op.f('ix_coins_symbol'), 'coins', ['symbol'], unique=False)
    op.create_index(op.f('ix_coins_coingekoid'), 'coins', ['coingekoid'], unique=True)
    op.create_index(op.f('ix_coins_name'), 'coins', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coins_name'), table_name='coins')
    op.drop_index(op.f('ix_coins_coingekoid'), table_name='coins')
    op.drop_index(op.f('ix_coins_symbol'), table_name='coins')
    op.create_index('ix_coins_symbol', 'coins', ['symbol'], unique=True)
    op.drop_column('coins', 'coingekoid')
    # ### end Alembic commands ###
