"""new migration

Revision ID: b430bbfe045f
Revises: 25fe0ffd85bc
Create Date: 2025-03-15 09:46:29.446326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b430bbfe045f'
down_revision: Union[str, None] = '25fe0ffd85bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('coingeckoid', sa.String(), nullable=False))
    op.drop_index('ix_coins_coingekoid', table_name='coins')
    op.create_index(op.f('ix_coins_coingeckoid'), 'coins', ['coingeckoid'], unique=True)
    op.drop_column('coins', 'coingekoid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('coingekoid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_coins_coingeckoid'), table_name='coins')
    op.create_index('ix_coins_coingekoid', 'coins', ['coingekoid'], unique=True)
    op.drop_column('coins', 'coingeckoid')
    # ### end Alembic commands ###
