"""Fix scoring weight relationship

Revision ID: 28cb5e065469
Revises: 05677a03cb73
Create Date: 2025-03-12 02:54:33.405791

"""
from typing import Sequence, Union

from scripts.alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28cb5e065469"
down_revision: Union[str, None] = "05677a03cb73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
